language: node_js
node_js: stable

#
before_install:
  - echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "小饼"
  - git config --global user.email i@iloxe.com

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-deployer-git --save

before_script:
  - hexo clean

# command to run tests
script:
  - hexo generate

after_success:
  - hexo deploy